apiVersion: v1
kind: Service
metadata:
  name: serv-feservice
  labels:
    domain: infra
    purpose: inframgmt
    app: cachingapp
spec:
  type: LoadBalancer
  selector:
    domain: backend
    purpose: fe-layer
    app: cachingapp
  ports:
    - port: 80
      targetPort: 80
